{{- range .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ . }}
  namespace: {{ $.Values.namespace }}
  ## Uncomment to enable automatic cascading deletes when an Application
  ## is removed.
  # finalizers:
  # - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ . }}
    name: {{ $.Values.spec.destination.name }}
  project: default
  source:
    path: {{ . }}
    repoURL: {{ $.Values.spec.source.repoURL }}
    targetRevision: {{ $.Values.spec.source.targetRevision }}
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
{{- end }}